on: 
  workflow_dispatch:

name: Dev-IaC-Workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      # Checkout code
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'dev'

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        # Specify the Az PowerShell script here.
        inlineScript: Get-AzSubscription
        # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
        azPSVersion: 6.4.0
        # Select the value of the ErrorActionPreference variable for executing the script. Options: stop, continue, silentlyContinue. Default is Stop.
        errorActionPreference: Stop
        # If this is true, this task will fail if any errors are written to the error pipeline, or if any data is written to the Standard Error stream.
        failOnStandardError: false
