on: 
  push:
    branches:
    - prod
name: Prod-IaC-PoC-Workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Prod
    steps:
      # Checkout code
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'prod'

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./ARMTemplates/storageaccount/azuredeploy.json
        parameters: ./ARMTemplates/storageaccount/parameters/Prod/azuredeploy.parameters.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
